trigger:
- none

variables:
- name: checkContext
  value: Pipeline validation
- name: checkDescription
  value: AzDO pipeline check - state.txt

resources:
  webhooks:
    - webhook: githubpr
      connection: github__pahealy7__apim-configuation__pr
  repositories:
    - repository: githubrepo
      type: github
      endpoint: phealy
      name: phealy/apim-configuration

pool:
  vmImage: ubuntu-latest

jobs:
- job: validatePullRequestType
  displayName: Validate PR type
  pool: server
  condition: in(${{ parameters.githubpr.action }}, 'opened', 'reopened', 'edited', 'synchronize')
  steps: []

- job: performCheckout
  displayName: Perform checkout
  dependsOn: validatePullRequestType
  steps:
  - checkout: githubrepo
    persistCredentials: true

  - script: |
      set -euxo pipefail
      git fetch origin pull/${{ parameters.githubpr.number }}/head:pr
      git checkout pr
      git status
    displayName: Switch branch to pull request head

  - script: |
      set -euxo pipefail
      echo '##vso[task.setvariable variable=pipelineResult]$(cat state.txt)'
    displayName: Perform checkout

  - script: |
      set -euxo pipefail
      # Post the state back to GitHub using our PAT
      # We can pull our Azure Pipelines PAT from the git config because we have
      # persistCredentials: true above
      GIT_REMOTE=$(git config --get remote.origin.url)
      GIT_AUTH=$(git config --get "http.${GIT_REMOTE}.extraheader")
      
      curl -H "Accept: application/vnd.github.v3+json" \
        -H "Content-Type: application/json" \
        -H "${GIT_AUTH}" \
        -X POST \
        '${{ parameters.githubpr.pull_request.statuses_url }}' \
        --data @- << EOF
      {
        "state":"$(pipelineResult)",
        "context":"$(checkContext),
        "description":"$(checkDescription)",
        "target_url":"$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)"
      }
      EOF
    displayName: Post commit status ($(pipelineResult))
