# Cross-repository GitHub pull request status check pipeline
# Patrick Healy, patrick.healy@microsoft.com
#
# Example implementation template for a pipeline.

trigger:
  - none

pr:
  - none

variables:
  # These are what show in the pull request status check line. The context
  # needs to be unique for the repository as it's the identifier used to set
  # the required status check.
  checkContext: Pipeline validation
  checkDescription: AzDO pipeline check

resources:
  # Incoming Webhook service connection
  webhooks:
    - webhook: githubpr
      connection: github__pahealy7__apim-configuration__pr
  # We need a repository resource to the repo we're running the pipeline
  # against, both so that we can get the code and so we can get an access
  # token to post the status back.
  repositories:
    - repository: githubrepo
      type: github
      endpoint: phealy
      name: phealy/apim-configuration

pool:
  vmImage: ubuntu-latest

extends:
  template: github_pr_pipeline.yml
  parameters:
    # Pass in required data
    # checkContext: $(checkContext)
    # checkDescription: $(checkDescription)
    githubpr: ${{ parameters.githubpr }}

    # Implement checkout tasks here - any failing step will cause the pipeline
    # to terminate and post a failure to the commit.
    checkoutSteps:
      - script: |
          # IMPLEMENT YOUR CHECKOUT TASK(S) HERE
          sleep 5
          # This example will fail in step 1 if the file "fail1" exists
          test -f fail1 && {
            echo '##vso[task.issue type=error;]Failed in checkout step 1.'
            echo '##vso[task.complete result=Failed;done=true;]'
          } || { true; }
        displayName: Perform checkout step 1

      - script: |
          # ANOTHER CHECKOUT TASK
          sleep 5
          # This example will fail in step 1 if the file "fail2" exists
          test -f fail2 && {
            echo '##vso[task.issue type=error;]Failed in checkout step 2.'
            echo '##vso[task.complete result=Failed;done=true;]'
          } || { true; }
        displayName: Perform checkout step 2
