trigger:
- none

variables:
- name: webhook
  value: github__pahealy7__apim-configuation__pr
- name: check_context
  value: demo_pipeline
- name: check_description
  value: AzDO pipeline check - state.txt

resources:
  webhooks:
    - webhook: github_pr
      connection: github__pahealy7__apim-configuation__pr
      filters:
        - path: action
          value: opened

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: true
- script: |
    set -x
    WEBHOOK_ACTION="${{ parameters.github_pr.action }}"
    GIT_REMOTE=$(git config --get remote.origin.url)
    GIT_AUTH=$(git config --get "http.${GIT_REMOTE}.extraheader")

    # Set auth for the PR repo
    git config --set "http.${{ parameters.pull_request.head.repo.clone_url }}.extraheader=$GIT_AUTH"

    git clone ${{ parameters.pull_request.head.repo.clone_url }} ref/pull/${{ parameters.number }}/head
  workingDirectory: $(Build.SourcesDirectory)
  displayName: Clone PR code
- script: |
    STATE=$(cat state.txt)
    
    curl \
      -H "Accept: application/vnd.github.v3+json" \
      -H "${GIT_AUTH}" \
      -X POST \
      -d "{\"context\": \"demo_pipeline\", \"description\": \"AzDO pipeline status check\", \"state\":\"$STATE\"}" \
      https://api.github.com/repos/phealy/apim-configuration/statuses/$(Build.SourceVersion)
    curl -H "Accept: application/vnd.github.v3+json" -H "${GIT_AUTH}" https://api.github.com/repos/phealy/apim-configuration/commits/$(Build.SourceVersion)/status
  workingDirectory: $(Build.SourcesDirectory)/${{ parameters.pull_request.head.repo.name }}
  displayName: 'Post commit status'
