trigger:
- none

variables:
- name: webhook
  value: github__pahealy7__apim-configuation__pr
- name: check_context
  value: demo_pipeline
- name: check_description
  value: AzDO pipeline check - state.txt

resources:
  webhooks:
    - webhook: githubpr
      connection: github__pahealy7__apim-configuation__pr

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: true
- script: |
    set -euxo pipefail

    if [[ -z "${{ parameters.githubpr.number }}" ]]; then
      echo "Not actually triggered from a PR, exiting."
      exit 0
    fi

    WEBHOOK_ACTION="${{ parameters.githubpr.action }}"
    GIT_REMOTE=$(git config --get remote.origin.url)
    GIT_AUTH=$(git config --get "http.${GIT_REMOTE}.extraheader")

    # Set auth for the PR repo
    git config --add "http.${{ parameters.githubpr.pull_request.head.repo.html_url }}.extraheader" "$GIT_AUTH"

    # Clone the PR repo
    git clone ${{ parameters.githubpr.pull_request.head.repo.clone_url }} 
    pushd ${{ parameters.githubpr.pull_request.head.repo.name }}
    git fetch origin ref/pull/${{ parameters.githubpr.number }}/head:pr
    git checkout pr
    git status

    STATE=$(cat state.txt)
    
    curl \
      -H "Accept: application/vnd.github.v3+json" \
      -H "${GIT_AUTH}" \
      -X POST \
      -d "{\"context\": \"demo_pipeline\", \"description\": \"AzDO pipeline status check\", \"state\":\"$STATE\"}" \
      ${{ parameters.githubpr.pull_request.head.repo.url }}/statuses/$(Build.SourceVersion)
    curl -H "Accept: application/vnd.github.v3+json" -H "${GIT_AUTH}" ${{ parameters.githubpr.pull_request.head.repo.url }}/commits/$(Build.SourceVersion)/status
  displayName: 'Post commit status'
