trigger:
- none

variables:
- name: webhook
  value: github__pahealy7__apim-configuation__pr
- name: check_context
  value: demo_pipeline
- name: check_description
  value: AzDO pipeline check - state.txt

resources:
  webhooks:
    - webhook: githubpr
      connection: github__pahealy7__apim-configuation__pr
  repositories:
    - repository: githubrepo
      type: github
      endpoint: phealy
      name: phealy/apim-configuration

pool:
  vmImage: ubuntu-latest

steps:
- checkout: githubrepo
  persistCredentials: true
- script: |
    set -euxo pipefail

    if [[ -z "${{ parameters.githubpr.number }}" ]]; then
      echo "Not actually triggered from a PR, exiting."
      exit 0
    fi

    WEBHOOK_ACTION="${{ parameters.githubpr.action }}"

    git fetch origin pull/${{ parameters.githubpr.number }}/head:pr
    git checkout pr
    git status

    STATE=$(cat state.txt)
    
    curl \
      -H "Accept: application/vnd.github.v3+json" \
      -H "${GIT_AUTH}" \
      -X POST \
      -d "{\"context\": \"demo_pipeline\", \"description\": \"AzDO pipeline status check\", \"state\":\"$STATE\"}" \
      ${{ parameters.githubpr.pull_request.head.repo.url }}/statuses/$(Build.SourceVersion)
    curl -H "Accept: application/vnd.github.v3+json" -H "${GIT_AUTH}" ${{ parameters.githubpr.pull_request.head.repo.url }}/commits/$(Build.SourceVersion)/status
  displayName: Post commit status
